spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted # 逻辑删除属性名
      logic-delete-value: 1 # 逻辑删除已删除值
      logic-not-delete-value: 0 # 逻辑删除未删除值
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

server:
  port: 8000
